### ISSUE TITLE
please provide a summary

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/statcheck#3]
I have run ./regression-test twice today to check Crispy Doom for demo compatibility and each over the 10902 ZIP files run took well between one and two hours.

When the tests were finally finished, the small status window simply closed and the following was printed into the terminal:

```
Traceback (most recent call last):
  File "./regression-test", line 127, in <module>
    pipeline.finish()
  File "/home/greffrath/Debian/statcheck/common.py", line 237, in finish
    self.poll()
  File "/home/greffrath/Debian/statcheck/common.py", line 196, in poll
    callback(p.exit_code, p.stdout, p.stderr)
  File "./regression-test", line 104, in process_complete
    success = check_output(output_filename, relpath, lmpname)
  File "./regression-test", line 55, in check_output
    expected = read_file(expected_file)
  File "./regression-test", line 42, in read_file
    stream = open(filename)
IOError: [Errno 2] No such file or directory: 'output/pwads/mm2/nmare/m215n650.zip/m215n650.txt'
```

I assume this message indicates a bug, but this is not what I complain about, though this is the reason I run the test a second time.

It would be very nice if the regression-test tool could print some results after finishing the tests. For example:

10902 ZIP files tested
10901 OK (99%)
1 Failed (1%)
This took 1:05:00
[OK]

It would be even better if it could keep track of the successful and failed tests, i.e. store the file names appended with an "OK" or "FAIL" into a text file, so I don't have to search for the string "fail" through why whole terminal buffer.

**Comment by fragglet** [comment]
I believe things should be a lot clearer now since I've rewritten the system to use GNU make (matching quickcheck). It's also a lot easier to set up. The old regression-test script is now gone. Take a look and if you're still confused, let me know.
