### ISSUE TITLE
please enable to run on only a subsets of the WADs

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/statcheck#4]
As I've written in my previous report, one whole test can easily take up more than an hour, whereas sometimes you may be only interested in the test results for e.g. av.wad -- which comes last. It should thus be possible to run the tests only over a subset of the WADs, like e.g. `./regression-test --wads doom2,av`.

**Comment by fragglet** [comment]
I believe you can already do this:

```
regression-test "doom2/*" "pwads/av/*"
```

**Comment by fabiangreffrath** [comment]
See, I'm a python dyslexic...

**Comment by fragglet** [comment]
You can learn Python, Fabian. I believe in you!

Seriously though, you won't regret it.

**Comment by fabiangreffrath** [comment]
I know, I know, I should really start to learn it. All I need is a project not too big to start with. Maybe this here is even the right one...
